[phases.setup]
nixPkgs = ['...', 'git', 'nodejs_18', 'nodePackages.pnpm']

[phases.build]
cmds = [
    'git clone https://github.com/immccn123/imken-link-web',
    'cd imken-link-web',
    'pnpm install',
    'pnpm build',
    'cp -r dist/* ../static/',
    'cd ..',
    'rm -r imken-link-web',
    '...'
]

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'
