import type { Metadata } from "next";
import { env } from "process";

import "semantic-ui-css/semantic.css";

export const metadata: Metadata = {
	title: env["SITE_NAME"] ?? "Imken Link",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
